/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package builddupdb2;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MediaTracker;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dennis
 */
public class ControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        initialize();
    }
    
    private void initialize(){
        //btnPhotoInsert.addActionListener(e -> performPhotoInsert());
        //btnPhotoInsert.setEnabled(false);
        btnBuildDB.addActionListener(e -> buildBasePhotoDB());
        
        jLabel2.setVisible(false);
        jLabel2.setBackground(Color.ORANGE);
        jLabel2.setText("");
                
        //ImageIcon baseFoto = new ImageIcon("k:\\testfoto.jpg");
        ImageIcon baseFoto = new ImageIcon("k:\\testicon.png");
        Image baseFotoImage = baseFoto.getImage();
        int baseFotoImageWidth = baseFoto.getIconWidth();
        int baseFotoImageHeigth = baseFoto.getIconHeight();
        float aspectRatio = (float)baseFotoImageWidth/(float)baseFotoImageHeigth;
        Dimension dim = jLabel2.getSize();
        jLabel2.getHeight();
        int y = dim.height;
        int x = dim.width;
        float newX =  (x * aspectRatio);
        int newWidth = (int) newX;
               
        Image newimg = baseFotoImage.getScaledInstance(newWidth, y,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        ImageIcon image3 = new ImageIcon(newimg);  
        //jLabel2.setBounds(0, 0, newWidth, y);
        jLabel2.setMinimumSize(new Dimension(newWidth, y));
        jLabel2.setMaximumSize(new Dimension(newWidth, y));
        jLabel2.setPreferredSize(new Dimension(newWidth, y));
        //jLabel2.setIcon(image3);
                
        
        
        //Dimension baseFotoSize = baseFotoImage.
        //Image image = background.getImage();
        //int p1 =  background.getImageLoadStatus();
        //int p2 =  background1.getImageLoadStatus();
        //background.ge 
        
        
        
        
        //Image image2 = background1.getImage(); // transform it 
       // Image newimg = image.getScaledInstance(x, y,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        //ImageIcon image3 = new ImageIcon(newimg);  

        int ok = MediaTracker.COMPLETE;
        int err = MediaTracker.ERRORED;
        int aborted = MediaTracker.ABORTED;
        
        
        //jLabel2.setBounds(0, 0, x, y);
        jLabel2.setIcon(image3);
        //JLabel label = new JLabel();
        //label.setBounds(0, 0, 250, 250);
        //label.setIcon(background);


        
        //baseImage.setLayout(null);
        //baseImage.add(label);
     
       //baseImage.add(background);
    }
    
    private void performPhotoInsert() {
        
        //new ExamineDups().setVisible(true);
        //System.out.println("Back in Control Panel");
    }
     private void buildBasePhotoDB() {
        
       
        Cursor oldCursor = getCursor();
        Cursor cursor = new Cursor(Cursor.WAIT_CURSOR); // HAND CURSOR
        setCursor(cursor);
        BuildDupsGuts dup = new BuildDupsGuts();
        setCursor(oldCursor);
        JOptionPane.showMessageDialog(this,
            dup.numDups + " duplicates found among \n." + 
            dup.numTotal + " files in " + dup.numFolders + " folders",
            "Build Photo DB",
             JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        btnBuildDB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Palibre Photo Manager");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Photo Organizer Control Panel");

        btnBuildDB.setText("Build Duplicates DB");

        jLabel2.setBackground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("jLabel2");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuildDB)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnBuildDB)
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
